version: '2'
services:
  web:
    image: "php:5.6"
    volumes:
     - .:/tmp
    command: php -S 0.0.0.0:80 -t /tmp
    networks:
      - fakebook
    ports:
      - "80:80"
  redis:
    image: "redis:3.0"
    networks:
      - fakebook
networks:
  fakebook:
    driver: bridge
